name = "ExtractPSF"
uuid = "387662ca-47fb-11e9-36d5-97ab6f05d7f8"
authors = ["Cody-G <codyjgreer@gmail.com>"]
version = "0.1.0"

[deps]
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
